/*  Message-number definitions derived from "ELWANNO.MSG"  */

#define PSTKEY      1
#define EDITKEY     2
#define PSTSEC      4
#define DOBEEP      5
#define EDITBUG     6
#define EDTNAM      7
#define VIEWSTG     8
#define EDITSTG     9
#define FSTLINE    10
#define LSTLINE    11
#define PRMSTR     12
#define PRMEND     13
#define SHOWAUD    14
#define SHOWTEXT   15
#define FILNAM     16
#define ADLOG      18
#define SORRY      19
#define HELP       20
#define RECS       21
#define NORECS     22
#define RECDAT     23
#define FLAGHDR    24
#define FLAG       25
#define RECDEL     26
#define RECADD     27
#define RSVNAM     28
